[tool.poetry]
name = "uc"
version = "0.1.0"
description = ""
authors = ["Patrik Persson <patrik95195@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
